
// route name + module + action

import { connect } from "react-redux";

export const GET_HONOR_LIST = 'GET_HONOR_LIST';
export const GET_GRADE_LIST = 'GET_GRADE_LIST';
export const GET_INTERNSHIP_LIST = 'GET_INTERNSHIP_LIST';
export const GET_ACADEMIC_LIST = 'GET_ACADEMIC_LIST';
export const GET_ARTICLEMANAGE_LIST = 'GET_ARTICLEMANAGE_LIST';

// POTRAITMANAGEMENT
export const POTRAITMANAGEMENT_TAB_CHANGE = 'POTRAITMANAGEMENT_TAB_CHANGE';

// EXPERIENCE
export const EXPERIENCE_GET_ARTICLE_LIST = 'EXPERIENCE_GET_ARTICLE_LIST';
export const EXPERIENCE_GET_TAG_LIST = 'EXPERIENCE_GET_TAG_LIST';
export const EXPERIENCE_TAG_AREA_CHANGE = 'EXPERIENCE_TAG_AREA_CHANGE';
export const EXPERIENCE_TAG_UNIVERSITY_CHANGE = 'EXPERIENCE_TAG_UNIVERSITY_CHANGE';
export const EXPERIENCE_TAG_MAJOR_CHANGE = 'EXPERIENCE_TAG_MAJOR_CHANGE';

// ARTICLE
export const ARTICLE_GET_DETAIL = 'ARTICLE_GET_DETAIL';
export const ADD_ARTICLE = 'ADD_ARTICL';
export const ADD_ARTICLE_GET_RECORD = 'ADD_ARTICLE_GET_RECORD';

export const ADDARTICLE_CHANGE_ADD_TITLE = 'ADDARTICLE_CHANGE_ADD_TITLE';
export const ADDARTICLE_CHANGE_ADD_DESC = 'ADDARTICLE_CHANGE_ADD_DESC';
export const ADDARTICLE_CHANGE_ADD_AREA = 'ADDARTICLE_CHANGE_ADD_AREA';
export const ADDARTICLE_CHANGE_ADD_UNIVERSITY = 'ADDARTICLE_CHANGE_ADD_UNIVERSITY';
export const ADDARTICLE_CHANGE_ADD_MAJOR = 'ADDARTICLE_CHANGE_ADD_MAJOR';
export const ADDARTICLE_CHANGE_ADD_IMG_URL = 'ADDARTICLE_CHANGE_ADD_IMG_URL';
export const ADDARTICLE_CHANGE_ADD_CONTENT = 'ADDARTICLE_CHANGE_ADD_CONTENT';


// ANNOUNCEMENT
export const ANNOUNCEMENT_GET_ANNOUNCEMENT_LIST = 'ANNOUNCEMENT_GET_ANNOUNCEMENT_LIST';
export const ANNOUNCEMENT_TYPE_CHANGE = 'ANNOUNCEMENT_TYPE_CHANGE';
export const ANNOUNCEMENT_KEYWORD_CHANGE = 'ANNOUNCEMENT_KEYWORD_CHANGE';

//GRADE
export const POTRAITMANAGEMENT_SHOW_EDIT_GRADE_DIALOG = 'POTRAITMANAGEMENT_SHOW_EDIT_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CLOSE_EDIT_GRADE_DIALOG = 'POTRAITMANAGEMENT_CLOSE_EDIT_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_COURSENAME = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_COURSENAME';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_SCORE = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_SCORE';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_GPA = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_GPA';
export const POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_ISMAJOR = 'POTRAITMANAGEMENT_CHANGE_EDIT_GRADE_ISMAJOR';
export const POTRAITMANAGEMENT_UPDATE_EDIT_GRADE = 'POTRAITMANAGEMENT_UPDATE_EDIT_GRADE';

export const POTRAITMANAGEMENT_SHOW_ADD_GRADE_DIALOG = 'POTRAITMANAGEMENT_SHOW_ADD_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CLOSE_ADD_GRADE_DIALOG = 'POTRAITMANAGEMENT_CLOSE_ADD_GRADE_DIALOG';
export const POTRAITMANAGEMENT_CHANGE_ADD_GRADE_COURSENAME = 'POTRAITMANAGEMENT_CHANGE_ADD_GRADE_COURSENAME';
export const POTRAITMANAGEMENT_CHANGE_ADD_GRADE_SCORE = 'POTRAITMANAGEMENT_CHANGE_ADD_GRADE_SCORE';
export const POTRAITMANAGEMENT_CHANGE_ADD_GRADE_GPA = 'POTRAITMANAGEMENT_CHANGE_ADD_GRADE_GPA';
export const POTRAITMANAGEMENT_CHANGE_ADD_GRADE_ISMAJOR = 'POTRAITMANAGEMENT_CHANGE_ADD_GRADE_ISMAJOR';
export const POTRAITMANAGEMENT_UPDATE_ADD_GRADE = 'POTRAITMANAGEMENT_UPDATE_ADD_GRADE';

export const POTRAITMANAGEMENT_DEL_GRADE = 'POTRAITMANAGEMENT_DEL_GRADE';

//INTERNSHIP
export const POTRAITMANAGEMENT_ADD_INTERNSHIP = 'POTRAITMANAGEMENT_ADD_INTERNSHIP';
export const POTRAITMANAGEMENT_DEL_INTERNSHIP = 'POTRAITMANAGEMENT_DEL_INTERNSHIP';
export const POTRAITMANAGEMENT_ADD_ACADEMIC = 'POTRAITMANAGEMENT_ADD_ACADEMIC';
export const POTRAITMANAGEMENT_DEL_ACADEMIC = 'POTRAITMANAGEMENT_DEL_ACADEMIC';
export const POTRAITMANAGEMENT_ADD_HONOR = 'POTRAITMANAGEMENT_ADD_HONOR';
export const POTRAITMANAGEMENT_DEL_HONOR = 'POTRAITMANAGEMENT_DEL_HONOR';

//ARTICLE
export const SAVE_ARTICLES_LIST = 'SAVE_ARTICLES_LIST';

//MASTER
export const MASTER_GET_MASTERINFO = 'MASTER_GET_MASTERINFO';

//MASTER_LOGIN
export const MASTER_LOGIN_IN = 'MASTER_LOGIN_IN';
export const MASTER_NAME_LOGIN_IN = 'MASTER_NAME_LOGIN_IN';
export const MASTER_PASSWORD_LOGIN_IN = 'MASTER_PASSWORD_LOGIN_IN';

//MASTER_REGISTER
export const MASTER_REGISTER = 'MASTER_REGISTER';
export const MASTER_REGISTER_NAME = 'MASTER_REGISTER_NAME';
export const MASTER_REGISTER_PASSWORD = 'MASTER_REGISTER_PASSWORD';
export const MASTER_REGISTER_UNDERGRADUATESCHOOL = 'MASTER_REGISTER_UNDERGRADUATESCHOOL';
export const MASTER_REGISTER_UNDERGRADUATEMAJOR = 'MASTER_REGISTER_UNDERGRADUATEMAJOR';
export const MASTER_REGISTER_MASTERSCHOOL = "MASTER_REGISTER_MASTERSCHOOL";
export const MASTER_REGISTER_MASTERAREA = "MASTER_REGISTER_MASTERAREA";
export const MASTER_REGISTER_MASTERMAJOR = "MASTER_REGISTER_MASTERMAJOR";
export const MASTER_REGISTER_ENROLLMENTDATE = "MASTER_REGISTER_ENROLLMENTDATE";

//ARTICLEMANAGE
export const ARTICLEMANAGE_DEL_ARTICLE = 'ARTICLEMANAGE_DEL_ARTICLE';

//USER_LOGIN
export const USER_LOGIN = 'USER_LOGIN';
export const USER_LOGIN_NAME = 'USER_LOGIN_NAME';
export const USER_LOGIN_PASSWORD = 'USER_LOGIN_PASSWORD';

//USER_REGISTER
export const USER_REGISTER = 'USER_REGISTER';
export const USER_REGISTER_NAME = 'USER_REGISTER_NAME';
export const USER_REGISTER_PASSWORD = 'USER_REGISTER_PASSWORD';